name: Deploy to Smithery

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m server --help
        
    - name: Build Docker image
      run: |
        docker build -t jama-abstract-generator .
        
    - name: Deploy to Smithery
      env:
        SMITHERY_API_KEY: ${{ secrets.SMITHERY_API_KEY }}
      run: |
        # Install Smithery CLI
        npm install -g @smithery/cli
        
        # Login to Smithery
        echo $SMITHERY_API_KEY | smithery login
        
        # Deploy using configuration
        smithery deploy --config smithery.yaml
        
    - name: Verify deployment
      run: |
        echo "Deployment completed. Check Smithery dashboard for status."
