name: Deploy to Smithery

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -c "import server; print('✅ Server import başarılı')"
        
    - name: Build Docker image
      run: |
        docker build -t jama-abstract-generator .
        
    - name: Test Docker image
      run: |
        docker run --rm jama-abstract-generator python -c "import server; print('✅ Docker container test başarılı')"
        
    - name: Deploy to Smithery
      env:
        SMITHERY_API_KEY: ${{ secrets.SMITHERY_API_KEY }}
      run: |
        echo "🚀 Smithery.ai'ye deployment başlıyor..."
        echo "📋 Deployment sonrası:"
        echo "   1. https://smithery.ai adresine gidin"
        echo "   2. GitHub ile giriş yapın"
        echo "   3. 'New Project' oluşturun"
        echo "   4. Repository: aliemregencer/jama-abstract-mcp-v3"
        echo "   5. Branch: main"
        echo "   6. Deploy butonuna tıklayın"
        
    - name: Verify deployment
      run: |
        echo "✅ Build ve test tamamlandı!"
        echo "🔗 Smithery.ai'de manuel deployment yapın:"
        echo "   https://smithery.ai"
